### ISSUE TITLE
Improve Roster Function

### ISSUE THREAD

**Issue by DingleBells** [DingleBells/OWL_Bot#1]
The roster function is making too many unnecessary requests to the overwatch league team sites. Every time you get a team's roster, the code requests the roster from all 20 teams. Try to tidy it up so that it only makes only one request for each team.

**Comment by ryankim0709** [comment]
I used elif statements so once it gets the team, it just breaks. Plus, it's return, so once it returns, then it brakes.

**Comment by DingleBells** [comment]
In the displayRoster.py file, there are too many code duplications with the elif statements. Please refactor it as follows:
`elif team == 'boston uprising' or team == 'uprising':
    return str(getBostonRoster())

  elif team == 'chengdu hunters' or team == 'hunters':
    return str(getChengouRoster())`

should be something like

`
teamname = team.split()[-1]
# Note that the dictionary will have the function name but not call it. 
# Also not that those functions already return strings
teamdict = {'uprising':getBostonRoster, 'hunters' = getChengduRoster, ...}
if teamname in teamdict:
     return teamdict[teamname]() # The value from the dictionary is a function, so it needs to be called with (). 
else:
     return "That is not an Overwatch League team."
`

**Comment by DingleBells** [comment]
In roster.py, the same code is repeated throughout the file. In lines 6-105, the basic format of the code is 
```
html = requests.get("https://teamname.overwatchleague.com/en-us/roster").text
soup = BeautifulSoup(html, 'html.parser')
roster = soup.find("script", {"id":"__NEXT_DATA__"})
data = json.loads(list(roster)[0])
``` 
, with the only difference being the team's name in the URL.
Instead of repeating the same lines, consider using a function such as 
```
def getRosterData(teamname):
     html = requests.get(f"https://{teamname}.overwatchleague.com/en-us/roster").text
     # rest of code here
```
to reduce the repetitiveness of the code. 

Also in this file from lines 117-175, all the functions only differ in the data that the function takes the roster from. Consider coding a function that will take a team's roster data and return the formatted version of the code. Remember to use the function above too. 


If these changes are implemented, displayRoster.py needs to be updated to match roster.py's format. In the findTeam function, the team name can be extracted from the "city team" and "team" variations of the input to see if the team exists. A team can be checked by comparing the name to a set with all the team names in it, like this:

```
def findTeam(input):
    name = input.split()[-1]
    teams = {"reign", "uprising", 'hunters', 'fuel', 'mayhem', 'charge', 'spark', ...}
    # check if name is in teams and execute code based on the result
```
Implementing these changes will speed up the code and make it more visually appealing.
